language: objective-c
env:
  global:
    - secure: "GaVQVOgt9a6u7XYKKeB4OhbEKzr+ZtQU+R5mg0ziXlwBz2cUvEKrjlvXxog3YzRSs4dVnpIjYx7iZmK7zWVtkqBgCk6ksPF33505iRSs3iOWWm71D+eYLltd3DJ/lDiJnBKlOWqJH1erzJrxDY5NEoa0EteYLhqf85ljL9OS/k4="
  matrix:
    - CC=clang CXX=clang++
    - CC=gcc CXX=g++
before_install:
  - export PROJECT_DIR=${TRAVIS_BUILD_DIR}
  - echo "${PROJECT_DIR}"
  - ./.travis/before_install.sh
install:
  - ./.travis/install.sh
before_script:
  - ./.travis/before_script.sh
script:
  - ./.travis/script.sh
after_success:
  - ./.travis/after_success.sh
after_failure:
  - ./.travis/after_failure.sh
after_script:
  - ./.travis/after_script.sh
