language: c
compiler:
  - clang
  - gcc
env:
  global:
    - secure: "GrvBB3X/FO+Wpw3E17WnXXAiCGqrYYvqNCl+y7QVMMXRsOr2EqbtR4yBGg41iDmHv7xcy60TlsQZFxF2jmW2WSs9LNvm3IIrp0HqLc0L/dQHhHESD7OyXTCXUqr+ydJO1uvbMqFjtfN/nCx+y7Rh93BTMkeGmFjdTCgDNQSgoYg="
before_install:
  - export PROJECT_DIR=${TRAVIS_BUILD_DIR}
  - echo "${PROJECT_DIR}"
  - ./.travis/before_install.sh
install:
  - ./.travis/install.sh
before_script:
  - ./.travis/before_script.sh
script:
  - ./.travis/script.sh
after_success:
  - ./.travis/after_success.sh
after_failure:
  - ./.travis/after_failure.sh
after_script:
  - ./.travis/after_script.sh
notifications:
  - webhooks:
    - urls:
      - https://e2qp70uqza5j.runscope.net
