language: c
compiler:
  - clang
  - gcc
before_install:
  - echo "${BASH_SOURCE}"
  - export PROJECT_DIR=${TRAVIS_BUILD_DIR}
  - echo "${PROJECT_DIR}"
  - ./.travis/before_install.sh
install:
  - ./.travis/install.sh
before_script:
  - ./.travis/before_script.sh
script:
  - ./.travis/script.sh
after_success:
  - ./.travis/after_success.sh
after_failure:
  - ./.travis/after_failure.sh
after_script:
  - ./.travis/after_script.sh
