language: c
compiler:
  - clang
  - gcc
env:
  global:
    - secure: "L4b7bTgkaMc1X8Xu65uL2/Q8KX/ihx+0VtBWowvrnYXMMI5ALwBBhcVoOS3BglUYR5X6sEoxrzNNiRv4F4CLD1KsTifaaCP0NhszIQH3A9UW5EuGGJPX4mrTE7q3OSJVg+KsqWeDUjhVZTOEAzS4nZN54JQtKCmYSixYM27KND4="


before_install:
  - uname -a
  - lsb_release --all
  - export PROJECT_DIR=${TRAVIS_BUILD_DIR}
  - sudo apt-get -qq update
  - sudo apt-get -qq autoremove
  - sudo apt-get -qq autoclean

install:
  - sudo apt-get -qq install autoconf
  - sudo apt-get -qq install autoconf-archive
  - sudo apt-get -qq install automake
  - sudo apt-get -qq install libboost-dev
  - sudo apt-get -qq install libtool

script:
  - export BUILD_DIR=`mktemp -d`
  - export PREFIX_DIR=`mktemp -d`
  - export PATH="${PREFIX_DIR}/bin:${PATH}"
  - cd ${BUILD_DIR}
  - autoreconf -ivf ${PROJECT_DIR}
  - ${PROJECT_DIR}/configure --prefix=${PREFIX_DIR}
  - make
  - make check
  - make distcheck
  - make install

after_success:
  - ./.travis/after_success.sh
after_failure:
  - ./.travis/after_failure.sh
after_script:
  - ./.travis/after_script.sh
notifications:
  irc:
    channels:
      - "irc.rizon.net#rubicks-test-travis"
    on_success: always
    on_failure: always
    on_start: true
    use_notice: true
  webhooks:
    urls:
      - http://webhookapp.com/1853108619478347874
      - http://e2qp70uqza5j.runscope.net/travis
    on_success: always
    on_failure: always
    on_start: true
