language: objective-c
env:
  global:
    - secure: "L4b7bTgkaMc1X8Xu65uL2/Q8KX/ihx+0VtBWowvrnYXMMI5ALwBBhcVoOS3BglUYR5X6sEoxrzNNiRv4F4CLD1KsTifaaCP0NhszIQH3A9UW5EuGGJPX4mrTE7q3OSJVg+KsqWeDUjhVZTOEAzS4nZN54JQtKCmYSixYM27KND4="
  matrix:
    - CC=clang CXX=clang++
    - CC=gcc CXX=g++
before_install:
  - export PROJECT_DIR=${TRAVIS_BUILD_DIR}
  - echo "${PROJECT_DIR}"
  - ./.travis/before_install.sh
install:
  - ./.travis/install.sh
before_script:
  - ./.travis/before_script.sh
script:
  - ./.travis/script.sh
after_success:
  - ./.travis/after_success.sh
after_failure:
  - ./.travis/after_failure.sh
after_script:
  - ./.travis/after_script.sh
notifications:
  irc:
    channels:
      - "irc.rizon.net#rubicks-test-travis"
    on_success: always
    on_failure: always
    on_start: true
    use_notice: true
  webhooks:
    urls:
      - http://webhookapp.com/1853108619478347874
      - http://e2qp70uqza5j.runscope.net/travis
    on_success: always
    on_failure: always
    on_start: true
